image: r-base

test:
  script:
    - R -e 'install.packages(c("tibble", "magrittr", "rvest", "purrr", "xml2", "urltools"))'
    - R CMD build . --no-build-vignettes --no-manual
    - R CMD check *tar.gz --no-build-vignettes --no-manual
